# Generated by Django 5.1 on 2024-09-02 10:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codedictionapp', '0023_remove_studentprofile_enrolled_courses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='codedictionapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/student')),
                ('dob', models.DateField(null=True)),
                ('location', models.TextField(null=True)),
                ('joining_date', models.DateTimeField(default=datetime.datetime.now)),
                ('enrolled_courses', models.ManyToManyField(related_name='enrolled_students', through='studentdashboard.Enrollment', to='codedictionapp.courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='studentdashboard.studentprofile'),
        ),
    ]
