from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Services)
admin.site.register(SubjectType)
admin.site.register(Subjects)
admin.site.register(CourseCategories)
admin.site.register(Courses)
admin.site.register(Curriculum)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(BlogCategory)
admin.site.register(Blog)
admin.site.register(OurBatch)
admin.site.register(OurClients)
admin.site.register(Testimonial)
admin.site.register(OurWork)
admin.site.register(WorkCategories)
admin.site.register(Contactus)
admin.site.register(SubscribeNewsletter)