# Generated by Django 5.0 on 2024-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='uploads/services'),
        ),
    ]
