# Generated by Django 5.0 on 2024-01-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0002_alter_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/services'),
        ),
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='uploads/services/icon'),
        ),
    ]
