# Generated by Django 5.0 on 2024-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0003_services_image_services_status_alter_services_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='meta_tags',
            new_name='meta_data',
        ),
        migrations.AddField(
            model_name='blog',
            name='brief',
            field=models.CharField(default='', max_length=255),
        ),
    ]
