# Generated by Django 5.0 on 2024-02-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0004_rename_desciption_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='meta_tags',
            new_name='meta_data',
        ),
    ]
