# Generated by Django 5.0 on 2024-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0005_rename_meta_tags_blogcategory_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='relation_with',
            field=models.ManyToManyField(blank=True, null=True, to='codedictionapp.subjects'),
        ),
    ]
