# Generated by Django 5.0 on 2024-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0006_alter_subjects_relation_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbatch',
            name='meta_data',
            field=models.TextField(null=True),
        ),
    ]
