# Generated by Django 5.0 on 2024-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0007_ourbatch_meta_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
