# Generated by Django 5.0 on 2024-02-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0008_alter_curriculum_options_curriculum_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstudents',
            name='batch',
            field=models.CharField(default='One To One Mentorship', max_length=255),
        ),
    ]
