# Generated by Django 5.0 on 2024-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0010_ourteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='subjects',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
