# Generated by Django 5.0 on 2024-02-13 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0013_subscribenewsletter_contactus_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscribenewsletter',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
