# Generated by Django 5.1 on 2024-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0017_alter_curriculum_options_remove_curriculum_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='meta_data',
            field=models.TextField(null=True),
        ),
    ]
