# Generated by Django 5.1 on 2024-09-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0022_alter_services_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
