# Generated by Django 5.1 on 2024-09-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedictionapp', '0023_remove_studentprofile_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
